In [1]:
"""
Neste vídeo será mostrado um exemplo de como construir vetores em python numpy
"""

import numpy as np
a = np.random.randn(5)

In [2]:
print(a)

[-0.13360703  1.28506633 -1.09851797  1.25052659  0.36989658]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)  # Matriz transposta

[-0.13360703  1.28506633 -1.09851797  1.25052659  0.36989658]


In [5]:
print(np.dot(a, a.T))  # Imprime o produto interno entre "a" e "a" transposto

4.576628281103455


In [7]:
a = np.random.randn(5, 1)  # Utilizar dessa forma ao invés de estrutura de
                           # dados
print(a)

[[-1.42412092]
 [ 1.63127353]
 [ 0.10761641]
 [ 1.9715508 ]
 [-1.06547871]]


In [8]:
print(a.T) # Note que agora são dois colchetes na estrutura de dados do vetor

[[-1.42412092  1.63127353  0.10761641  1.9715508  -1.06547871]]


In [10]:
print(np.dot(a, a.T))

[[ 2.02812038 -2.32313076 -0.15325877 -2.80772673  1.51737051]
 [-2.32313076  2.66105334  0.17555179  3.21613864 -1.73808721]
 [-0.15325877  0.17555179  0.01158129  0.21217121 -0.11466299]
 [-2.80772673  3.21613864  0.21217121  3.88701257 -2.1006454 ]
 [ 1.51737051 -1.73808721 -0.11466299 -2.1006454   1.13524488]]


Recatiputalando

In [17]:
# O primeiro comando foi:
a = np.random.randn(5)  # Isso é chamado de matriz de ordem 1
print(a)


[ 1.31579838  0.36787735 -1.4602755   0.27624652 -0.85783468]
